---
# Common action for all states.
- name: generate intented variables
  tags: [always]
  inventory_to_container:
    inventory: 'inventory.yml'
    container_root: '{{ container_root }}'
    configlet_dir: 'intended_configs'
    configlet_prefix: '{{ configlets_prefix }}'
    destination: '{{playbook_dir}}/generated_vars/{{inventory_hostname}}.yml'
  register: CVP_VARS

- name: 'Build DEVICES and CONTAINER definition for {{inventory_hostname}}'
  tags: [build]
  template:
    src: "cvp-devices.j2"
    dest: './generated_vars/{{inventory_hostname}}.yml'
  delegate_to: localhost
  run_once: true

- name: "Load CVP device information for {{inventory_hostname}}"
  tags: [build, provision]
  include_vars: '{{playbook_dir}}/generated_vars/{{inventory_hostname}}.yml'
  # delegate_to: localhost

#################################################

# If state=present launch creation/update process
- name: Start creation/update process.
  include_tasks: ./present.yml
  when: state=="present"

#################################################

# If state=absent launch deletion process
- name: Start deletion process.
  include_tasks: ./absent.yml
  when: state=="absent"