port_profiles:

  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"

  TENANT_A:
    mode: access
    vlans: "110"

  TENANT_B:
    mode: trunk
    vlans: "210-211"


servers:

  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [ Eth0 ]
        switch_ports: [ Ethernet12 ]
        switches: [ DC1-LEAF1A ]
        profile: TENANT_A

  server02:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [ Eth0 ]
        switch_ports: [ Ethernet12 ]
        switches: [ DC1-LEAF2B ]
        profile: TENANT_A